apiVersion: v2
type: application
name: cert-manager-webhook-google-domains
description: Allow cert-manager to solve DNS challenges using Google Domains DNS

version: 0.0.0-template
appVersion: 0.0.0-template

icon: https://domains.google/static/images/logo/new_logo.svg
home: https://github.com/nblxa/cert-manager-webhook-google-domains/chart

sources:
- https://github.com/nblxa/cert-manager-webhook-google-domains

keywords:
- cert-manager
- google-domains
- webhook
- tls
- dns

maintainers:
- name: nblxa
  email: pavel@mitrofanov.cloud
